<?php

namespace app\models;

use Yii;
use app\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/**
 * This is the model class for table "carousel".
 *
 * @property integer $id
 * @property string $name
 * @property string $short_description
 * @property string $picture
 * @property string $url
 * @property integer $order
 * @property integer $status
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 */
class Carousel extends BaseActiveRecord
{
    public $pictureFile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carousel';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'short_description', 'url', 'order'], 'required'],
            [['order', 'status', 'created_by', 'updated_by'], 'integer'],
            [['picture', 'created_at', 'updated_at'], 'safe'],
            [['name', 'url'], 'string', 'max' => 100],
            [['short_description'], 'string', 'max' => 200],
            [['picture'], 'string', 'max' => 150],
            ['order', 'default', 'value'=>0],
            [['pictureFile'], 'file', 'extensions'=>['jpg', 'png'], 'skipOnEmpty'=>false, 'checkExtensionByMimeType'=>false, 'maxSize'=>1024*1024*4, 'tooBig'=>'Limit is 4MB', 'on'=>self::SCENARIO_INSERT],
            [['pictureFile'], 'file', 'extensions'=>['jpg', 'png'], 'skipOnEmpty'=>true, 'checkExtensionByMimeType'=>false, 'maxSize'=>1024*1024*4, 'tooBig'=>'Limit is 4MB', 'on'=>self::SCENARIO_UPDATE],
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isStatusActive())
            $this->status = self::STATUS_ACTIVE;
        else
            $this->status = self::STATUS_NON_ACTIVE;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $this->deletePicture();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'short_description' => 'Short Description',
            'picture' => 'Picture',
            'url' => 'Url',
            'order' => 'Order',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    public function getPictureName() {
        $label = Url::createSlug($this->name);
        $uploadedFile   = md5(date('Ymd H:i:s')). '.' . $this->pictureFile->extension;
        $fileName       = "{$label}-{$uploadedFile}";  // random number + file name
        return $fileName;
    }

    /**
     * @return string
     */
    public function getPictureUrl()
    {
        $path = 'web/data/images/carousel/' . $this->picture;

        if (!file_exists(Yii::getAlias('@app/' . $path))) {
            return 'http://placehold.it/1414x944';
        }

        return Url::to('@' . $path, true);
    }

    public function getPictureHtml($options=['style'=>'width:80px;'])
    {
        $options = ArrayHelper::merge(['alt'=>$this->name], $options);
        return Html::img($this->getPictureUrl(), $options);
    }

    private function deletePicture()
    {
        @unlink(Yii::$app->basePath."/web/data/images/carousel/".$this->picture);
    }

    /**
     * @return bool
     */
    public function validatePictureFile()
    {
        if(!$this->validate()) {
            return false;
        }

        if(!$this->isNewRecord) {
            if($this->pictureFile) {
                $this->deletePicture();
            } else {
                return true;
            }
        }

        $this->picture = $this->getPictureName();
        $this->pictureFile->saveAs('data/images/carousel/'.$this->picture);
        return true;
    }

    /**
     * @return bool
     */
    public function isStatusActive()
    {
        if(!empty($this->name) && !empty($this->picture) && !empty($this->short_description) && !empty($this->url))
        {
            return true;
        }
        return false;
    }
}