<?php

namespace app\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "education".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $url
 * @property string $start_date
 * @property string $end_date
 * @property integer $education_status
 * @property integer $status
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 */
class Education extends BaseActiveRecord
{
    const EDUCATION_STATUS_GRADUATE = 2;
    const EDUCATION_STATUS_ACTIVE = 1;
    const EDUCATION_STATUS_NON_ACTIVE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'education';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'url', 'start_date'], 'required'],
            [['id', 'education_status', 'status', 'created_by', 'updated_by'], 'integer'],
            [['description'], 'string'],
            [['start_date', 'end_date', 'created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 100],
            [['url'], 'string', 'max' => 150],
            ['education_status', 'default', 'value' => self::EDUCATION_STATUS_GRADUATE],
            ['status', 'default', 'value'=>self::STATUS_ACTIVE],
        ];
    }

    public function beforeSave($insert)
    {
        if(empty($this->end_date)) {
            $this->education_status = self::EDUCATION_STATUS_ACTIVE;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'url' => 'Url',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'education_status' => 'Education Status',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    public static function educationStatusLabels()
    {
        return [
            self::EDUCATION_STATUS_GRADUATE => 'GRADUATE',
            self::EDUCATION_STATUS_ACTIVE => 'ACTIVE',
            self::EDUCATION_STATUS_NON_ACTIVE => 'NON ACTIVE',
        ];
    }

    public function getEducationStatusLabel()
    {
        return self::educationStatusLabels()[$this->education_status];
    }

    public function getEducationStatusWithStyle()
    {
        switch ($this->education_status) {
            case self::EDUCATION_STATUS_GRADUATE : return Html::label($this->getEducationStatusLabel(), null, ['class'=>'label label-primary']);
            case self::EDUCATION_STATUS_ACTIVE : return Html::label($this->getEducationStatusLabel(), null, ['class'=>'label label-success']);
            case self::EDUCATION_STATUS_NON_ACTIVE : return Html::label($this->getEducationStatusLabel(), null, ['class'=>'label label-danger']);
        }
    }
}
