<?php

namespace app\models;

use Yii;
use app\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "portfolio".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $url
 * @property string $date
 * @property string $picture
 * @property integer $client_id
 * @property integer $status
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property Client $client
 * @property Tag $tags
 * @property PortfolioHasTag $portfolioHasTags
 */
class Portfolio extends \app\models\BaseActiveRecord
{
    public $pictureFile;
    public $inputTags;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'portfolio';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'url', 'date', 'client_id'], 'required'],
            [['description'], 'string'],
            [['date', 'inputTags', 'created_at', 'updated_at'], 'safe'],
            [['client_id', 'status', 'created_by', 'updated_by'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['url'], 'string', 'max' => 150],
            [['picture'], 'string', 'max' => 200],
            ['status', 'default', 'value'=>self::STATUS_ACTIVE],
            [['pictureFile'], 'file', 'extensions'=>['jpg', 'png'], 'skipOnEmpty'=>false, 'checkExtensionByMimeType'=>false, 'maxSize'=>1024*1024*4, 'tooBig'=>'Limit is 4MB', 'on'=>self::SCENARIO_INSERT],
            [['pictureFile'], 'file', 'extensions'=>['jpg', 'png'], 'skipOnEmpty'=>true, 'checkExtensionByMimeType'=>false, 'maxSize'=>1024*1024*4, 'tooBig'=>'Limit is 4MB', 'on'=>self::SCENARIO_UPDATE],
        ];
    }

    public function beforeDelete()
    {
        $this->deletePicture();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($this->tags) {
            PortfolioHasTag::deleteAll(['portfolio_id'=>$this->id]);
        }

        foreach($this->inputTags as $tag) {
            $portfolioHasTag = new PortfolioHasTag();
            $portfolioHasTag->portfolio_id = $this->id;
            $portfolioHasTag->tag_id = $tag;
            $portfolioHasTag->save();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'url' => 'Url',
            'date' => 'Date',
            'picture' => 'Picture',
            'client_id' => 'Client ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id'=>'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPortfolioHasTags()
    {
        return $this->hasMany(PortfolioHasTag::className(), ['portfolio_id'=>'id']);
    }

    /**
     * @return $this
     */
    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id'=>'tag_id'])->via('portfolioHasTags');
    }

    public function getPictureName() {
        $label = Url::createSlug($this->name);
        $uploadedFile   = md5(date('Ymd H:i:s')). '.' . $this->pictureFile->extension;
        $fileName       = "{$label}-{$uploadedFile}";  // random number + file name
        return $fileName;
    }

    /**
     * @return string
     */
    public function getPictureUrl()
    {
        $path = 'web/data/images/portfolio/' . $this->picture;

        if (!file_exists(Yii::getAlias('@app/' . $path))) {
            return 'http://placehold.it/400x200';
        }

        return Url::to('@' . $path, true);
    }

    public function getPictureHtml($options=['style'=>'width:80px;'])
    {
        $options = ArrayHelper::merge(['alt'=>$this->name], $options);
        return Html::img($this->getPictureUrl(), $options);
    }

    private function deletePicture()
    {
        @unlink(Yii::$app->basePath."/web/data/images/portfolio/".$this->picture);
    }

    /**
     * @return bool
     */
    public function validatePictureFile()
    {
        if(!$this->validate()) {
            return false;
        }

        if(!$this->isNewRecord) {
            if($this->pictureFile) {
                $this->deletePicture();
            } else {
                return true;
            }
        }

        $this->picture = $this->getPictureName();
        $this->pictureFile->saveAs('data/images/portfolio/'.$this->picture);
        return true;
    }
}
